format = '''
$username[@](cyan bold)$hostname$directory$git_branch$git_status
[\$](bold green) '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[username]
style_user = 'yellow bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
style = 'blue bold'
ssh_only = false
disabled = false
